First commit documentApi
liveasy97/documentApi pull request #2
Opened 2021-05-24 13:33 UTC by vivekbhosale

2021-05-29 18:30 UTC, jsrub requested changes
there are some big changes left. Please correct them.

2021-05-29 18:30 UTC, jsrub commented on DocumentAPI/src/main/java/com/springboot/DocumentAPI/Services/DocServiceImpl.java
> +	    String docId = "Doc:"+UUID.randomUUID();
shouldn't this be in small case? "doc"

2021-05-29 18:30 UTC, jsrub commented on DocumentAPI/src/main/java/com/springboot/DocumentAPI/Services/DocServiceImpl.java
> +		DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd MMM, yyyy");
this configuration should not be here. either make a util function to get current time or put this in the constructor itself.

2021-05-29 18:30 UTC, jsrub commented on DocumentAPI/src/main/java/com/springboot/DocumentAPI/Services/DocServiceImpl.java
> +	    for(int i=0;i<mainDoc.getData().size();i++) {
don't iterate in this manner. instead do something like this 
for(Integer item : state.testData){
    result.add(item);
  }

2021-05-29 18:30 UTC, jsrub commented on DocumentAPI/src/main/java/com/springboot/DocumentAPI/Services/DocServiceImpl.java
> +	public DocumentCreateResponse addDocument(MultipartFile[] file, MainDocForPost mainDoc) {
the arguments don't seem right. Why would the api user be sending link in the request? Please confirm this with doc.

2021-05-29 18:30 UTC, jsrub commented on DocumentAPI/src/main/java/com/springboot/DocumentAPI/Services/DocServiceImpl.java
> +			URL url = client.getUrl(bucketname, file[i].getOriginalFilename());
i think these operations should be execute in async. Since in sync they will block the api response. Lets use kafka to send the upload request to and then consume the messages in kafka. After consuming the message the file will be uploaded. This way we can ensure that the api doesn't get blocked. And more than one user can access these apis at a time. You can read a bit about kafka on the below links. 
https://www.tutorialspoint.com/apache_kafka/apache_kafka_introduction.htm
https://www.confluent.io/blog/apache-kafka-spring-boot-application/

2021-05-29 18:30 UTC, jsrub commented on DocumentAPI/src/main/resources/application.yml
> +cloud:
what is the use of this file?

2021-06-07 20:44 UTC, liveasy97 approved these changes

2021-06-07 20:44 UTC, merged